# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://theory1.shaffermusic.com
title: Music Theory 1
email: kris.shaffer@colorado.edu
description: "MUSC 1101, CU–Boulder"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/krisshaffer
  - title: github
    url: https://github.com/kshaffer/theory1
